import { storage } from "../storage";
const FORBIDDEN_IMAGE_TERMS = [
  "organ",
  "organs",
  "heart",
  "lungs",
  "brain",
  "liver",
  "kidney",
  "stomach",
  "intestine",
  "colon",
  "blood",
  "vein",
  "artery",
  "surgery",
  "medical",
  "anatomy",
  "x-ray",
  "scan",
  "mri",
  "skeleton",
  "muscle",
  "nerve",
  "tumor",
  "wound",
  "injury",
  "disease",
  "hospital",
  "clinic",
  "doctor",
  "patient",
];

function normalizeImagePrompt(prompt: string): string {
  let p = prompt.toLowerCase();

  // Any health → convert to nature & lifestyle
  p = p.replace(
    /brain|mind|mental|cognitive|neural|focus|memory|clarity/g,
    "calm",
  );
  p = p.replace(
    /health|healthy|wellness|medical|healing|therapy/g,
    "peaceful lifestyle",
  );
  p = p.replace(/body|human|person|people|face|head/g, "scene");

  return p;
}

function isSafeImagePrompt(prompt: string): boolean {
  const p = prompt.toLowerCase();
  return !FORBIDDEN_IMAGE_TERMS.some((term) => p.includes(term));
}

export interface AiImageResult {
  url: string;
  credit: string;
  provider: string;
}

interface NovitaResponse {
  images?: Array<{
    image_url?: string;
    image_url_ttl?: number;
  }>;
  image_urls?: string[];
  task_id?: string;
  status?: string;
  code?: number;
  msg?: string;
  message?: string;
}

interface NovitaTaskResponse {
  task?: {
    status?: string;
    progress?: number;
  };
  images?: Array<{
    image_url?: string;
    image_url_ttl?: number;
  }>;
  code?: number;
  msg?: string;
}

export async function generateAiImage(
  prompt: string,
  model: string,
  novitaApiKey: string,
  campaignId?: number,
): Promise<AiImageResult | null> {
  if (!novitaApiKey) {
    throw new Error("Novita API key not configured");
  }

  try {
    // Use async endpoint for qwen-image-txt2img model
    const endpoint = `https://api.novita.ai/v3/async/qwen-image-txt2img`;

    console.log(
      `[AI Image] Generating image with qwen-image-txt2img, endpoint: ${endpoint}`,
    );

    let safePrompt = normalizeImagePrompt(prompt);

    if (!isSafeImagePrompt(safePrompt)) {
      console.warn("[AI Image] Unsafe prompt blocked:", safePrompt);

      safePrompt =
        "A peaceful, healthy, uplifting wellness scene with plants, natural sunlight, warm colors, and a calm happy mood. No people, no medical elements, no body parts, no anatomy. Nature-inspired, clean, beautiful.";
    }

    const enhancedPrompt = `${safePrompt}. Ultra high quality, bright, modern, friendly.`;

    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${novitaApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt: enhancedPrompt,
        negative_prompt:
          "people, person, human, face, body, skin, anatomy, organs, brain, heart, blood, medical, hospital, doctor, patient, surgery, skeleton, muscle, nerve, x-ray, scan",
        size: "1024*1024",
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(`[AI Image] API error: ${response.status} - ${errorText}`);
      throw new Error(`Novita API error: ${response.status} - ${errorText}`);
    }

    const data: NovitaResponse = await response.json();
    console.log(`[AI Image] Response:`, JSON.stringify(data).substring(0, 500));

    if (data.code && data.code !== 0) {
      throw new Error(
        `Novita API error: ${data.msg || data.message || "Unknown error"}`,
      );
    }

    // Handle async task response
    if (data.task_id) {
      console.log(
        `[AI Image] Got task_id: ${data.task_id}, polling for result...`,
      );
      const imageUrl = await pollForResult(data.task_id, novitaApiKey);
      if (imageUrl) {
        if (campaignId) {
          await storage.createLog({
            campaignId,
            level: "info",
            message: `AI image generated successfully using qwen-image-txt2img`,
            metadata: { prompt: prompt.substring(0, 100), url: imageUrl },
          });
        }
        return {
          url: imageUrl,
          credit: `AI generated by Novita AI (qwen-image-txt2img)`,
          provider: "novita-ai",
        };
      }
    }

    // Handle image_urls array format
    if (data.image_urls && data.image_urls.length > 0) {
      const imageUrl = data.image_urls[0];
      console.log(
        `[AI Image] Got image from image_urls: ${imageUrl.substring(0, 100)}...`,
      );
      if (campaignId) {
        await storage.createLog({
          campaignId,
          level: "info",
          message: `AI image generated successfully using qwen-image-txt2img`,
          metadata: { prompt: prompt.substring(0, 100), url: imageUrl },
        });
      }
      return {
        url: imageUrl,
        credit: `AI generated by Novita AI (qwen-image-txt2img)`,
        provider: "novita-ai",
      };
    }

    // Handle direct image response (images array format)
    if (data.images && data.images.length > 0 && data.images[0].image_url) {
      const imageUrl = data.images[0].image_url;
      console.log(
        `[AI Image] Got image from images array: ${imageUrl.substring(0, 100)}...`,
      );
      if (campaignId) {
        await storage.createLog({
          campaignId,
          level: "info",
          message: `AI image generated successfully using qwen-image-txt2img`,
          metadata: { prompt: prompt.substring(0, 100), url: imageUrl },
        });
      }
      return {
        url: imageUrl,
        credit: `AI generated by Novita AI (qwen-image-txt2img)`,
        provider: "novita-ai",
      };
    }

    console.error(
      "[AI Image] No image found in response:",
      JSON.stringify(data),
    );
    throw new Error("No image returned from Novita API");
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error("[AI Image] Generation failed:", errorMessage);

    if (campaignId) {
      await storage.createLog({
        campaignId,
        level: "error",
        message: `AI image generation failed: ${errorMessage}`,
        metadata: { prompt: prompt.substring(0, 100), model },
      });
    }

    throw error;
  }
}

async function pollForResult(
  taskId: string,
  apiKey: string,
): Promise<string | null> {
  const maxAttempts = 60;
  const pollInterval = 2000;

  for (let i = 0; i < maxAttempts; i++) {
    await new Promise((resolve) => setTimeout(resolve, pollInterval));

    const response = await fetch(
      `https://api.novita.ai/v3/async/task-result?task_id=${taskId}`,
      {
        headers: {
          Authorization: `Bearer ${apiKey}`,
        },
      },
    );

    if (!response.ok) {
      continue;
    }

    const data: NovitaTaskResponse = await response.json();

    if (data.task?.status === "TASK_STATUS_SUCCEED") {
      if (data.images && data.images.length > 0 && data.images[0].image_url) {
        return data.images[0].image_url;
      }
    } else if (data.task?.status === "TASK_STATUS_FAILED") {
      throw new Error("Image generation task failed");
    }
  }

  throw new Error("Image generation timed out");
}

export function generateImagePrompt(caption: string, topic: string): string {
  const cleanCaption = caption
    .replace(/#\w+/g, "")
    .replace(/https?:\/\/\S+/g, "")
    .replace(/\n+/g, " ")
    .trim()
    .substring(0, 200);

  return `Create a clean, positive, Instagram-friendly health image about ${topic}. ${cleanCaption}. No organs, no medical scenes, no disgusting or scary content, no logos, no app icons, no any icons, no text. The image should look healthy, happy, bright, and natural, with a light and friendly mood and gentle wellness-style humor. High quality, vibrant colors, engaging composition, modern design.`;
}
